services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: familytree
      POSTGRES_USER: family
      POSTGRES_PASSWORD: tree
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
