spring:
  application:
    name: family-tree-api
  datasource:
    url: jdbc:postgresql://localhost:5432/familytree
    username: family
    password: family
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate.format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

  profiles:
    include: local

  data:
    redis:
      host: localhost
      port: 6379
      password: yourpassword
      database: 0

management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: 8080

auth:
  telegram:
    bot-username: ${BOT_USERNAME:my_family_bot}
    session-ttl-seconds: ${TELEGRAM_SESSION_TTL:300}
    webhook-secret: ${BOT_WEBHOOK_SECRET:my-secret-token}
    bot-token: ${BOT_TOKEN:bot_token}
  jwt:
    issuer: ${JWT_ISSUER:family-tree}
    access-ttl-seconds: ${JWT_ACCESS_TTL:900}
    refresh-ttl-seconds: ${JWT_REFRESH_TTL:2592000}
    # Подключайте ключи через переменные окружения / секрет-менеджер
    public-key-pem: ${JWT_PUBLIC_PEM:}
    private-key-pem: ${JWT_PRIVATE_PEM:}
