spring:
  application:
    name: family-tree-api
  datasource:
    url: jdbc:postgresql://localhost:5432/familytree
    username: family
    password: family
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate.format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

  profiles:
    include: local

  data:
    redis:
      host: localhost
      port: 6379
      password: yourpassword
      database: 0

management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: 8080

auth:
  telegram:
    bot-username: ${BOT_USERNAME:my_family_bot}
    session-ttl-seconds: ${TELEGRAM_SESSION_TTL:300}
    webhook-secret: ${BOT_WEBHOOK_SECRET:my-secret-token}

